# Generated by Django 4.1.6 on 2023-02-23 13:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('dob', models.CharField(default=None, max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None)),
                ('occupation', models.CharField(choices=[('ST', 'Student'), ('BS', 'Business'), ('CE', 'Corporate'), ('UD', 'Unemployed'), ('OS', 'Others')], default='ST', max_length=2)),
                ('membership', models.CharField(choices=[('MR', 'Minister'), ('WR', 'Worker'), ('MB', 'Member'), ('FR', 'First timer')], default='MR', max_length=2)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('ME', 'Male'), ('FE', 'Female')], default='ME', max_length=2)),
                ('profile_img', models.FileField(blank=True, default=None, null=True, unique=True, upload_to='images')),
            ],
        ),
    ]
